import Head from "next/head";
import React, { useEffect } from "react";
import Aos from "aos";
import { About, Benefit, Footer, Header, Hero, Partner } from "../components/organisms";
import 'aos/dist/aos.css' 

export default function Home() {
  useEffect(() => {
    Aos.init();
    console.log('aos', Aos)
  }, [])
  return (
    <>
      <Head>
        <title>CatLabsNFT - NFT Ticketing Platform</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-h-screen bg-black">
        <Header />
        <Hero />
        <About />
        <Benefit />
        <Partner />
        
        <Footer />
      </main>
    </>
  );
}
